/* Карта процессов: два издания на одной сетке.
 * Вертикаль в 6-м — области знаний, в 8-м — домены; горизонталь одна и та же,
 * пять фокус-областей. Поэтому одна разметка обслуживает оба режима. */
window.PMBOK = {
  fa: [
    { id: 'I',  t: 'Initiating' },
    { id: 'P',  t: 'Planning' },
    { id: 'E',  t: 'Executing' },
    { id: 'MC', t: 'Monitoring and Controlling' },
    { id: 'C',  t: 'Closing' }
  ],

  /* PMBOK 6 — 49 процессов, 10 областей знаний */
  ka6: [
    { id: 'int', t: 'Integration',   c: 'var(--d-gov)' },
    { id: 'sco', t: 'Scope',         c: 'var(--d-scope)' },
    { id: 'sch', t: 'Schedule',      c: 'var(--d-sched)' },
    { id: 'cos', t: 'Cost',          c: 'var(--d-fin)' },
    { id: 'qua', t: 'Quality',       c: '#C2477A' },
    { id: 'res', t: 'Resource',      c: 'var(--d-res)' },
    { id: 'com', t: 'Communications',c: '#C0492A' },
    { id: 'ris', t: 'Risk',          c: 'var(--d-risk)' },
    { id: 'pro', t: 'Procurement',   c: '#9A6A2B' },
    { id: 'stk', t: 'Stakeholder',   c: 'var(--d-stake)' }
  ],
  p6: [
    ['4.1','int','I','Develop Project Charter'],
    ['4.2','int','P','Develop Project Management Plan'],
    ['4.3','int','E','Direct and Manage Project Work'],
    ['4.4','int','E','Manage Project Knowledge'],
    ['4.5','int','MC','Monitor and Control Project Work'],
    ['4.6','int','MC','Perform Integrated Change Control'],
    ['4.7','int','C','Close Project or Phase'],
    ['5.1','sco','P','Plan Scope Management'],
    ['5.2','sco','P','Collect Requirements'],
    ['5.3','sco','P','Define Scope'],
    ['5.4','sco','P','Create WBS'],
    ['5.5','sco','MC','Validate Scope'],
    ['5.6','sco','MC','Control Scope'],
    ['6.1','sch','P','Plan Schedule Management'],
    ['6.2','sch','P','Define Activities'],
    ['6.3','sch','P','Sequence Activities'],
    ['6.4','sch','P','Estimate Activity Durations'],
    ['6.5','sch','P','Develop Schedule'],
    ['6.6','sch','MC','Control Schedule'],
    ['7.1','cos','P','Plan Cost Management'],
    ['7.2','cos','P','Estimate Costs'],
    ['7.3','cos','P','Determine Budget'],
    ['7.4','cos','MC','Control Costs'],
    ['8.1','qua','P','Plan Quality Management'],
    ['8.2','qua','E','Manage Quality'],
    ['8.3','qua','MC','Control Quality'],
    ['9.1','res','P','Plan Resource Management'],
    ['9.2','res','P','Estimate Activity Resources'],
    ['9.3','res','E','Acquire Resources'],
    ['9.4','res','E','Develop Team'],
    ['9.5','res','E','Manage Team'],
    ['9.6','res','MC','Control Resources'],
    ['10.1','com','P','Plan Communications Management'],
    ['10.2','com','E','Manage Communications'],
    ['10.3','com','MC','Monitor Communications'],
    ['11.1','ris','P','Plan Risk Management'],
    ['11.2','ris','P','Identify Risks'],
    ['11.3','ris','P','Perform Qualitative Risk Analysis'],
    ['11.4','ris','P','Perform Quantitative Risk Analysis'],
    ['11.5','ris','P','Plan Risk Responses'],
    ['11.6','ris','E','Implement Risk Responses'],
    ['11.7','ris','MC','Monitor Risks'],
    ['12.1','pro','P','Plan Procurement Management'],
    ['12.2','pro','E','Conduct Procurements'],
    ['12.3','pro','MC','Control Procurements'],
    ['13.1','stk','I','Identify Stakeholders'],
    ['13.2','stk','P','Plan Stakeholder Engagement'],
    ['13.3','stk','E','Manage Stakeholder Engagement'],
    ['13.4','stk','MC','Monitor Stakeholder Engagement']
  ],

  /* PMBOK 8 — 40 процессов, 7 доменов, книжный порядок */
  dom8: [
    { id: 'gov', t: 'Governance',   c: 'var(--d-gov)' },
    { id: 'sco', t: 'Scope',        c: 'var(--d-scope)' },
    { id: 'sch', t: 'Schedule',     c: 'var(--d-sched)' },
    { id: 'fin', t: 'Finance',      c: 'var(--d-fin)' },
    { id: 'stk', t: 'Stakeholders', c: 'var(--d-stake)' },
    { id: 'res', t: 'Resources',    c: 'var(--d-res)' },
    { id: 'ris', t: 'Risk',         c: 'var(--d-risk)' }
  ],
  /* [name, domain, focus area, status, предшественники в 6-м] */
  p8: [
    ['Initiate Project or Phase','gov','I','renamed',['4.1']],
    ['Integrate and Align Project Plans','gov','P','renamed',['4.2']],
    ['Plan Sourcing Strategy','gov','P','moved',['12.1']],
    ['Manage Project Execution','gov','E','renamed',['4.3']],
    ['Manage Quality Assurance','gov','E','moved',['8.2','8.1','8.3']],
    ['Manage Project Knowledge','gov','E','same',['4.4']],
    ['Monitor and Control Project Performance','gov','MC','renamed',['4.5']],
    ['Assess and Implement Changes','gov','MC','renamed',['4.6']],
    ['Close Project or Phase','gov','C','same',['4.7']],

    ['Plan Scope Management','sco','P','same',['5.1']],
    ['Elicit and Analyze Requirements','sco','P','renamed',['5.2']],
    ['Define Scope','sco','P','same',['5.3']],
    ['Develop Scope Structure','sco','P','renamed',['5.4']],
    ['Monitor and Control Scope','sco','MC','renamed',['5.6']],
    ['Validate Scope','sco','MC','same',['5.5']],

    ['Plan Schedule Management','sch','P','same',['6.1']],
    ['Develop Schedule','sch','P','merged',['6.2','6.3','6.4','6.5']],
    ['Monitor and Control Schedule','sch','MC','renamed',['6.6']],

    ['Plan Financial Management','fin','P','renamed',['7.1']],
    ['Estimate Costs','fin','P','same',['7.2']],
    ['Develop Budget','fin','P','renamed',['7.3']],
    ['Monitor and Control Finances','fin','MC','renamed',['7.4']],

    ['Identify Stakeholders','stk','I','same',['13.1']],
    ['Plan Stakeholder Engagement','stk','P','same',['13.2']],
    ['Plan Communications Management','stk','P','moved',['10.1']],
    ['Manage Stakeholder Engagement','stk','E','same',['13.3']],
    ['Manage Communications','stk','E','moved',['10.2']],
    ['Monitor Stakeholder Engagement','stk','MC','same',['13.4']],
    ['Monitor Communications','stk','MC','moved',['10.3']],

    ['Plan Resource Management','res','P','same',['9.1']],
    ['Estimate Resources','res','P','renamed',['9.2']],
    ['Acquire Resources','res','E','moved',['9.3','12.2']],
    ['Lead the Team','res','E','merged',['9.4','9.5']],
    ['Monitor and Control Resourcing','res','MC','moved',['9.6','12.3']],

    ['Plan Risk Management','ris','P','same',['11.1']],
    ['Identify Risks','ris','P','same',['11.2']],
    ['Perform Risk Analysis','ris','P','merged',['11.3','11.4']],
    ['Plan Risk Responses','ris','P','same',['11.5']],
    ['Implement Risk Responses','ris','E','same',['11.6']],
    ['Monitor Risks','ris','MC','same',['11.7']]
  ],

  status: {
    same:    { t: 'Unchanged',            c: '#9AA1AD' },
    renamed: { t: 'Renamed / restated',   c: 'var(--act)' },
    merged:  { t: 'Merged from several',  c: 'var(--warn)' },
    moved:   { t: 'Moved to another area',c: 'var(--d-stake)' },
    gone:    { t: 'No longer a process',  c: 'var(--gone)' }
  }
};

/* ── композиция плаката ────────────────────────────────────────────
   Пять контейнеров фокус-областей. Взаимное расположение как в оригинале
   Варгаса: Planning и M&C друг над другом справа (между ними самый плотный
   обмен), Executing слева отдаёт наверх и направо короткими дугами. */
PMBOK.canvas = { w: 2560, h: 1780 };
PMBOK.boxes = {
  I:  { x: 40,   y: 60,   w: 620,  h: 250,  t: 'Initiating' },
  P:  { x: 720,  y: 60,   w: 1800, h: 840,  t: 'Planning' },
  E:  { x: 40,   y: 360,  w: 620,  h: 700,  t: 'Executing' },
  MC: { x: 720,  y: 950,  w: 1800, h: 780,  t: 'Monitoring & Controlling' },
  C:  { x: 40,   y: 1560, w: 620,  h: 170,  t: 'Closing' }
};

/* Связи задаются по названию процесса — так они переживают перенумерацию.
   'back' — обратная связь, рисуется пунктиром. */
/* Звʼязки 8-ї редакції звірено з таблицями Inputs/Outputs Guide (розділ 2):
   стрілка A → B стоїть лише тоді, коли артефакт із виходів A названо серед
   входів B (у коментарі — за яким саме). Загальні контейнери (Project management
   plan, Project documents, EEF/OPA, Change requests) звʼязком не вважаються;
   винятки — Work performance information → Monitor and Control Project
   Performance, Work performance reports → Assess and Implement Changes і
   допоміжні плани → Integrate and Align Project Plans («Outputs from other
   processes»). 'back' — ціль у ранішій фазі, малюється пунктиром. */
/* Звʼязки 8-ї редакції звірено з таблицями Inputs/Outputs Guide (розділ 2):
   стрілка A → B стоїть лише тоді, коли артефакт із виходів A названо серед
   входів B (у коментарі — за яким саме). Підпункти під «… updates» виходами
   не вважаються: допоміжні плани збирає Integrate and Align Project Plans
   (Plan-процеси віддають йому «Project management plan updates»), і вже
   звідти план іде як складова Project management plan у кожен процес, що
   називає її на вході. Загальні контейнери (Project documents, EEF/OPA,
   Change requests) звʼязком не вважаються; винятки — Work performance
   information → Monitor and Control Project Performance і Work performance
   reports → Assess and Implement Changes. 'back' — ціль у ранішій фазі. */
PMBOK.links8 = [
  ['Initiate Project or Phase','Identify Stakeholders']  /* project charter */,
  ['Identify Stakeholders','Elicit and Analyze Requirements']  /* stakeholder register */,
  ['Identify Stakeholders','Identify Risks']  /* stakeholder register */,
  ['Identify Stakeholders','Perform Risk Analysis']  /* stakeholder register */,
  ['Identify Stakeholders','Plan Communications Management']  /* stakeholder register */,
  ['Identify Stakeholders','Plan Resource Management']  /* stakeholder register */,
  ['Identify Stakeholders','Plan Risk Management']  /* stakeholder register */,
  ['Identify Stakeholders','Plan Risk Responses']  /* stakeholder register */,
  ['Identify Stakeholders','Plan Scope Management']  /* stakeholder register */,
  ['Identify Stakeholders','Plan Sourcing Strategy']  /* stakeholder register */,
  ['Identify Stakeholders','Plan Stakeholder Engagement']  /* stakeholder register */,
  ['Initiate Project or Phase','Define Scope']  /* assumption log, project charter */,
  ['Initiate Project or Phase','Develop Schedule']  /* assumption log, project charter */,
  ['Initiate Project or Phase','Elicit and Analyze Requirements']  /* assumption log, project charter */,
  ['Initiate Project or Phase','Estimate Resources']  /* assumption log */,
  ['Initiate Project or Phase','Identify Risks']  /* assumption log */,
  ['Initiate Project or Phase','Integrate and Align Project Plans']  /* project charter */,
  ['Initiate Project or Phase','Perform Risk Analysis']  /* assumption log */,
  ['Initiate Project or Phase','Plan Communications Management']  /* project charter */,
  ['Initiate Project or Phase','Plan Financial Management']  /* project charter */,
  ['Initiate Project or Phase','Plan Resource Management']  /* project charter */,
  ['Initiate Project or Phase','Plan Risk Management']  /* project charter */,
  ['Initiate Project or Phase','Plan Schedule Management']  /* project charter */,
  ['Initiate Project or Phase','Plan Scope Management']  /* project charter */,
  ['Initiate Project or Phase','Plan Stakeholder Engagement']  /* assumption log, project charter */,
  ['Identify Stakeholders','Acquire Resources']  /* stakeholder register */,
  ['Identify Stakeholders','Manage Communications']  /* stakeholder register */,
  ['Identify Stakeholders','Manage Project Knowledge']  /* stakeholder register */,
  ['Identify Stakeholders','Manage Stakeholder Engagement']  /* stakeholder register */,
  ['Identify Stakeholders','Monitor Stakeholder Engagement']  /* stakeholder register */,
  ['Initiate Project or Phase','Monitor and Control Project Performance']  /* assumption log */,
  ['Initiate Project or Phase','Close Project or Phase']  /* assumption log, project charter */,
  ['Define Scope','Identify Stakeholders','back']  /* requirements documentation */,
  ['Elicit and Analyze Requirements','Identify Stakeholders','back']  /* requirements documentation */,
  ['Integrate and Align Project Plans','Identify Stakeholders','back']  /* project management plan */,
  ['Define Scope','Develop Scope Structure']  /* project scope statement, requirements documentation */,
  ['Define Scope','Identify Risks']  /* requirements documentation */,
  ['Define Scope','Plan Communications Management']  /* requirements documentation */,
  ['Define Scope','Plan Resource Management']  /* requirements documentation */,
  ['Define Scope','Plan Scope Management']  /* requirements documentation */,
  ['Define Scope','Plan Sourcing Strategy']  /* requirements documentation */,
  ['Develop Budget','Identify Risks']  /* cost baseline */,
  ['Develop Budget','Perform Risk Analysis']  /* cost baseline */,
  ['Develop Schedule','Develop Budget']  /* project schedule */,
  ['Develop Schedule','Estimate Costs']  /* project schedule */,
  ['Develop Schedule','Estimate Resources']  /* project schedule */,
  ['Develop Schedule','Identify Risks']  /* schedule baseline */,
  ['Develop Schedule','Integrate and Align Project Plans']  /* project management plan updates */,
  ['Develop Schedule','Perform Risk Analysis']  /* schedule baseline */,
  ['Develop Schedule','Plan Resource Management']  /* project schedule */,
  ['Develop Schedule','Plan Risk Responses']  /* project schedule */,
  ['Develop Schedule','Plan Stakeholder Engagement']  /* project schedule */,
  ['Develop Scope Structure','Develop Budget']  /* scope baseline */,
  ['Develop Scope Structure','Estimate Costs']  /* scope baseline */,
  ['Develop Scope Structure','Estimate Resources']  /* scope baseline */,
  ['Develop Scope Structure','Identify Risks']  /* scope baseline */,
  ['Develop Scope Structure','Perform Risk Analysis']  /* scope baseline */,
  ['Develop Scope Structure','Plan Resource Management']  /* scope baseline */,
  ['Elicit and Analyze Requirements','Define Scope']  /* requirements documentation */,
  ['Elicit and Analyze Requirements','Develop Scope Structure']  /* requirements documentation */,
  ['Elicit and Analyze Requirements','Identify Risks']  /* requirements documentation */,
  ['Elicit and Analyze Requirements','Plan Communications Management']  /* requirements documentation */,
  ['Elicit and Analyze Requirements','Plan Resource Management']  /* requirements documentation */,
  ['Elicit and Analyze Requirements','Plan Scope Management']  /* requirements documentation */,
  ['Elicit and Analyze Requirements','Plan Sourcing Strategy']  /* requirements documentation */,
  ['Estimate Costs','Develop Budget']  /* basis of estimates, cost estimates */,
  ['Estimate Costs','Develop Schedule']  /* basis of estimates */,
  ['Estimate Costs','Estimate Resources']  /* cost estimates */,
  ['Estimate Costs','Identify Risks']  /* cost estimates */,
  ['Estimate Costs','Perform Risk Analysis']  /* cost estimates */,
  ['Estimate Resources','Develop Budget']  /* basis of estimates */,
  ['Estimate Resources','Develop Schedule']  /* basis of estimates, resource requirements */,
  ['Estimate Resources','Estimate Costs']  /* resource requirements */,
  ['Estimate Resources','Identify Risks']  /* resource requirements */,
  ['Estimate Resources','Perform Risk Analysis']  /* resource requirements */,
  ['Estimate Resources','Plan Sourcing Strategy']  /* resource requirements */,
  ['Identify Risks','Develop Budget']  /* risk register */,
  ['Identify Risks','Develop Schedule']  /* risk register */,
  ['Identify Risks','Estimate Costs']  /* risk register */,
  ['Identify Risks','Estimate Resources']  /* risk register */,
  ['Identify Risks','Perform Risk Analysis']  /* risk register */,
  ['Identify Risks','Plan Resource Management']  /* risk register */,
  ['Identify Risks','Plan Risk Responses']  /* risk report */,
  ['Identify Risks','Plan Scope Management']  /* risk register */,
  ['Identify Risks','Plan Sourcing Strategy']  /* risk register */,
  ['Identify Risks','Plan Stakeholder Engagement']  /* risk register */,
  ['Integrate and Align Project Plans','Develop Budget']  /* project management plan */,
  ['Integrate and Align Project Plans','Develop Schedule']  /* project management plan */,
  ['Integrate and Align Project Plans','Elicit and Analyze Requirements']  /* project management plan */,
  ['Integrate and Align Project Plans','Estimate Costs']  /* project management plan */,
  ['Integrate and Align Project Plans','Estimate Resources']  /* project management plan */,
  ['Integrate and Align Project Plans','Identify Risks']  /* project management plan */,
  ['Integrate and Align Project Plans','Perform Risk Analysis']  /* project management plan */,
  ['Integrate and Align Project Plans','Plan Communications Management']  /* project management plan */,
  ['Integrate and Align Project Plans','Plan Financial Management']  /* project management plan */,
  ['Integrate and Align Project Plans','Plan Resource Management']  /* project management plan */,
  ['Integrate and Align Project Plans','Plan Risk Management']  /* project management plan */,
  ['Integrate and Align Project Plans','Plan Risk Responses']  /* project management plan */,
  ['Integrate and Align Project Plans','Plan Schedule Management']  /* project management plan */,
  ['Integrate and Align Project Plans','Plan Stakeholder Engagement']  /* project management plan */,
  ['Plan Communications Management','Integrate and Align Project Plans']  /* project management plan updates */,
  ['Plan Financial Management','Develop Budget']  /* financial management plan */,
  ['Plan Financial Management','Identify Risks']  /* financial management plan */,
  ['Plan Financial Management','Plan Sourcing Strategy']  /* financial management plan */,
  ['Plan Resource Management','Integrate and Align Project Plans']  /* project management plan updates */,
  ['Plan Risk Management','Identify Risks']  /* risk management plan */,
  ['Plan Risk Management','Perform Risk Analysis']  /* risk management plan */,
  ['Plan Risk Management','Plan Financial Management']  /* risk management plan */,
  ['Plan Risk Management','Plan Risk Responses']  /* risk management plan */,
  ['Plan Risk Management','Plan Stakeholder Engagement']  /* risk management plan */,
  ['Plan Risk Responses','Integrate and Align Project Plans']  /* project management plan updates */,
  ['Plan Schedule Management','Integrate and Align Project Plans']  /* project management plan updates */,
  ['Plan Scope Management','Integrate and Align Project Plans']  /* project management plan updates */,
  ['Plan Stakeholder Engagement','Integrate and Align Project Plans']  /* project management plan updates */,
  ['Develop Budget','Acquire Resources']  /* cost baseline */,
  ['Develop Schedule','Acquire Resources']  /* project schedule */,
  ['Develop Schedule','Lead the Team']  /* project schedule */,
  ['Develop Schedule','Manage Project Execution']  /* project schedule */,
  ['Develop Schedule','Manage Stakeholder Engagement']  /* project schedule */,
  ['Estimate Resources','Acquire Resources']  /* resource requirements */,
  ['Estimate Resources','Manage Project Knowledge']  /* resource breakdown */,
  ['Identify Risks','Implement Risk Responses']  /* risk register, risk report */,
  ['Identify Risks','Manage Communications']  /* risk report */,
  ['Identify Risks','Manage Project Execution']  /* risk register, risk report */,
  ['Identify Risks','Manage Stakeholder Engagement']  /* risk register */,
  ['Integrate and Align Project Plans','Acquire Resources']  /* project management plan */,
  ['Integrate and Align Project Plans','Implement Risk Responses']  /* project management plan */,
  ['Integrate and Align Project Plans','Lead the Team']  /* project management plan */,
  ['Integrate and Align Project Plans','Manage Communications']  /* project management plan */,
  ['Integrate and Align Project Plans','Manage Project Execution']  /* project management plan */,
  ['Integrate and Align Project Plans','Manage Project Knowledge']  /* project management plan */,
  ['Integrate and Align Project Plans','Manage Stakeholder Engagement']  /* project management plan */,
  ['Plan Resource Management','Lead the Team']  /* team charter */,
  ['Plan Risk Management','Implement Risk Responses']  /* risk management plan */,
  ['Plan Risk Management','Manage Stakeholder Engagement']  /* risk management plan */,
  ['Define Scope','Monitor and Control Scope']  /* requirements documentation */,
  ['Define Scope','Validate Scope']  /* requirements documentation */,
  ['Develop Budget','Assess and Implement Changes']  /* cost baseline */,
  ['Develop Budget','Monitor and Control Finances']  /* cost baseline, project funding requirements */,
  ['Develop Schedule','Assess and Implement Changes']  /* schedule baseline */,
  ['Develop Schedule','Monitor and Control Resourcing']  /* project schedule */,
  ['Develop Schedule','Monitor and Control Schedule']  /* project calendars, project schedule */,
  ['Develop Scope Structure','Assess and Implement Changes']  /* scope baseline */,
  ['Develop Scope Structure','Monitor and Control Schedule']  /* scope baseline */,
  ['Develop Scope Structure','Validate Scope']  /* scope baseline */,
  ['Elicit and Analyze Requirements','Monitor and Control Scope']  /* requirements documentation */,
  ['Elicit and Analyze Requirements','Validate Scope']  /* requirements documentation */,
  ['Estimate Costs','Assess and Implement Changes']  /* basis of estimates */,
  ['Estimate Costs','Monitor and Control Project Performance']  /* basis of estimates */,
  ['Estimate Resources','Assess and Implement Changes']  /* basis of estimates */,
  ['Estimate Resources','Monitor and Control Project Performance']  /* basis of estimates */,
  ['Estimate Resources','Monitor and Control Resourcing']  /* resource breakdown */,
  ['Identify Risks','Assess and Implement Changes']  /* risk report */,
  ['Identify Risks','Monitor Risks']  /* risk register, risk report */,
  ['Identify Risks','Monitor Stakeholder Engagement']  /* risk register */,
  ['Identify Risks','Monitor and Control Project Performance']  /* risk register, risk report */,
  ['Identify Risks','Monitor and Control Resourcing']  /* risk register */,
  ['Identify Risks','Monitor and Control Schedule']  /* risk register */,
  ['Integrate and Align Project Plans','Assess and Implement Changes']  /* project management plan */,
  ['Integrate and Align Project Plans','Monitor Communications']  /* project management plan */,
  ['Integrate and Align Project Plans','Monitor Risks']  /* project management plan */,
  ['Integrate and Align Project Plans','Monitor Stakeholder Engagement']  /* project management plan */,
  ['Integrate and Align Project Plans','Monitor and Control Finances']  /* project management plan */,
  ['Integrate and Align Project Plans','Monitor and Control Project Performance']  /* project management plan */,
  ['Integrate and Align Project Plans','Monitor and Control Resourcing']  /* project management plan */,
  ['Integrate and Align Project Plans','Monitor and Control Scope']  /* project management plan */,
  ['Plan Financial Management','Monitor and Control Finances']  /* financial management plan */,
  ['Plan Risk Management','Monitor Risks']  /* risk management plan */,
  ['Define Scope','Close Project or Phase']  /* requirements documentation */,
  ['Elicit and Analyze Requirements','Close Project or Phase']  /* requirements documentation */,
  ['Estimate Costs','Close Project or Phase']  /* basis of estimates */,
  ['Estimate Resources','Close Project or Phase']  /* basis of estimates */,
  ['Identify Risks','Close Project or Phase']  /* risk register, risk report */,
  ['Integrate and Align Project Plans','Close Project or Phase']  /* project management plan */,
  ['Manage Project Execution','Identify Stakeholders','back']  /* issue log */,
  ['Acquire Resources','Develop Schedule','back']  /* project team assignments, resource calendars */,
  ['Acquire Resources','Estimate Resources','back']  /* resource calendars */,
  ['Acquire Resources','Plan Risk Responses','back']  /* project team assignments, resource calendars */,
  ['Acquire Resources','Plan Sourcing Strategy','back']  /* project team assignments */,
  ['Manage Project Execution','Identify Risks','back']  /* issue log */,
  ['Manage Project Execution','Plan Stakeholder Engagement','back']  /* issue log */,
  ['Manage Project Knowledge','Develop Schedule','back']  /* lessons learned register */,
  ['Manage Project Knowledge','Elicit and Analyze Requirements','back']  /* lessons learned register */,
  ['Manage Project Knowledge','Estimate Costs','back']  /* lessons learned register */,
  ['Manage Project Knowledge','Identify Risks','back']  /* lessons learned register */,
  ['Manage Project Knowledge','Plan Risk Responses','back']  /* lessons learned register */,
  ['Acquire Resources','Lead the Team']  /* resource calendars */,
  ['Acquire Resources','Manage Project Knowledge']  /* project team assignments */,
  ['Manage Communications','Manage Project Execution']  /* project communications */,
  ['Manage Project Execution','Implement Risk Responses']  /* issue log */,
  ['Manage Project Execution','Lead the Team']  /* issue log */,
  ['Manage Project Execution','Manage Communications']  /* issue log */,
  ['Manage Project Execution','Manage Project Knowledge']  /* deliverables */,
  ['Manage Project Execution','Manage Stakeholder Engagement']  /* issue log */,
  ['Manage Project Knowledge','Implement Risk Responses']  /* lessons learned register */,
  ['Manage Project Knowledge','Manage Communications']  /* lessons learned register */,
  ['Manage Project Knowledge','Manage Project Execution']  /* lessons learned register */,
  ['Manage Project Knowledge','Manage Stakeholder Engagement']  /* lessons learned register */,
  ['Acquire Resources','Monitor and Control Resourcing']  /* physical or virtual resource assignments */,
  ['Acquire Resources','Monitor and Control Schedule']  /* resource calendars */,
  ['Implement Risk Responses','Monitor and Control Project Performance']  /* work performance information */,
  ['Manage Communications','Monitor Communications']  /* project communications */,
  ['Manage Communications','Monitor Stakeholder Engagement']  /* project communications */,
  ['Manage Project Execution','Monitor Communications']  /* issue log */,
  ['Manage Project Execution','Monitor Risks']  /* issue log */,
  ['Manage Project Execution','Monitor Stakeholder Engagement']  /* issue log */,
  ['Manage Project Execution','Monitor and Control Project Performance']  /* issue log */,
  ['Manage Project Execution','Monitor and Control Resourcing']  /* issue log */,
  ['Manage Project Execution','Monitor and Control Scope']  /* deliverables */,
  ['Manage Project Knowledge','Monitor Communications']  /* lessons learned register */,
  ['Manage Project Knowledge','Monitor Risks']  /* lessons learned register */,
  ['Manage Project Knowledge','Monitor Stakeholder Engagement']  /* lessons learned register */,
  ['Manage Project Knowledge','Monitor and Control Finances']  /* lessons learned register */,
  ['Manage Project Knowledge','Monitor and Control Project Performance']  /* lessons learned register */,
  ['Manage Project Knowledge','Monitor and Control Resourcing']  /* lessons learned register */,
  ['Manage Project Knowledge','Monitor and Control Schedule']  /* lessons learned register */,
  ['Manage Quality Assurance','Monitor and Control Project Performance']  /* quality reports */,
  ['Manage Quality Assurance','Validate Scope']  /* quality reports */,
  ['Manage Communications','Close Project or Phase']  /* project communications */,
  ['Manage Project Execution','Close Project or Phase']  /* issue log */,
  ['Manage Project Knowledge','Close Project or Phase']  /* lessons learned register */,
  ['Manage Quality Assurance','Close Project or Phase']  /* quality reports */,
  ['Assess and Implement Changes','Manage Project Execution','back']  /* approved change requests */,
  ['Assess and Implement Changes','Monitor and Control Scope']  /* approved change requests */,
  ['Monitor Communications','Monitor and Control Project Performance']  /* work performance information */,
  ['Monitor Risks','Monitor and Control Project Performance']  /* work performance information */,
  ['Monitor Stakeholder Engagement','Monitor and Control Project Performance']  /* work performance information */,
  ['Monitor and Control Finances','Monitor and Control Project Performance']  /* work performance information */,
  ['Monitor and Control Project Performance','Assess and Implement Changes']  /* work performance reports */,
  ['Monitor and Control Resourcing','Monitor and Control Project Performance']  /* work performance information */,
  ['Monitor and Control Schedule','Monitor and Control Project Performance']  /* schedule forecasts, work performance information */,
  ['Monitor and Control Scope','Monitor and Control Project Performance']  /* quality reports, work performance information */,
  ['Monitor and Control Scope','Validate Scope']  /* quality control measurements, quality reports, verified deliverables */,
  ['Validate Scope','Monitor and Control Project Performance']  /* work performance information */,
  ['Monitor and Control Scope','Close Project or Phase']  /* quality control measurements, quality reports */,
  ['Validate Scope','Close Project or Phase']  /* accepted deliverables */
];

PMBOK.links6 = [
  ['Develop Project Charter','Identify Stakeholders'],
  ['Develop Project Charter','Develop Project Management Plan'],
  ['Identify Stakeholders','Plan Stakeholder Engagement'],
  ['Develop Project Management Plan','Plan Scope Management'],
  ['Develop Project Management Plan','Plan Schedule Management'],
  ['Develop Project Management Plan','Plan Cost Management'],
  ['Develop Project Management Plan','Plan Quality Management'],
  ['Develop Project Management Plan','Plan Resource Management'],
  ['Develop Project Management Plan','Plan Risk Management'],
  ['Develop Project Management Plan','Plan Procurement Management'],
  ['Develop Project Management Plan','Plan Communications Management'],
  ['Plan Scope Management','Collect Requirements'],
  ['Collect Requirements','Define Scope'],
  ['Define Scope','Create WBS'],
  ['Create WBS','Define Activities'],
  ['Plan Schedule Management','Define Activities'],
  ['Define Activities','Sequence Activities'],
  ['Sequence Activities','Estimate Activity Durations'],
  ['Estimate Activity Durations','Develop Schedule'],
  ['Estimate Activity Resources','Estimate Activity Durations'],
  ['Plan Resource Management','Estimate Activity Resources'],
  ['Plan Cost Management','Estimate Costs'],
  ['Estimate Costs','Determine Budget'],
  ['Create WBS','Estimate Costs'],
  ['Plan Risk Management','Identify Risks'],
  ['Identify Risks','Perform Qualitative Risk Analysis'],
  ['Perform Qualitative Risk Analysis','Perform Quantitative Risk Analysis'],
  ['Perform Quantitative Risk Analysis','Plan Risk Responses'],
  ['Plan Risk Responses','Determine Budget'],
  ['Plan Risk Responses','Implement Risk Responses'],
  ['Plan Resource Management','Acquire Resources'],
  ['Acquire Resources','Develop Team'],
  ['Develop Team','Manage Team'],
  ['Plan Quality Management','Manage Quality'],
  ['Plan Procurement Management','Conduct Procurements'],
  ['Plan Stakeholder Engagement','Manage Stakeholder Engagement'],
  ['Plan Communications Management','Manage Communications'],
  ['Develop Project Management Plan','Direct and Manage Project Work'],
  ['Develop Schedule','Direct and Manage Project Work'],
  ['Determine Budget','Direct and Manage Project Work'],
  ['Direct and Manage Project Work','Manage Project Knowledge'],
  ['Direct and Manage Project Work','Monitor and Control Project Work'],
  ['Manage Quality','Control Quality'],
  ['Create WBS','Control Scope'],
  ['Develop Schedule','Control Schedule'],
  ['Determine Budget','Control Costs'],
  ['Acquire Resources','Control Resources'],
  ['Conduct Procurements','Control Procurements'],
  ['Implement Risk Responses','Monitor Risks'],
  ['Manage Stakeholder Engagement','Monitor Stakeholder Engagement'],
  ['Manage Communications','Monitor Communications'],
  ['Control Scope','Monitor and Control Project Work'],
  ['Control Schedule','Monitor and Control Project Work'],
  ['Control Costs','Monitor and Control Project Work'],
  ['Control Quality','Monitor and Control Project Work'],
  ['Control Resources','Monitor and Control Project Work'],
  ['Monitor Risks','Monitor and Control Project Work'],
  ['Monitor and Control Project Work','Perform Integrated Change Control'],
  ['Perform Integrated Change Control','Develop Project Management Plan','back'],
  ['Perform Integrated Change Control','Direct and Manage Project Work','back'],
  ['Control Quality','Validate Scope'],
  ['Validate Scope','Close Project or Phase'],
  ['Monitor and Control Project Work','Close Project or Phase']
];
